name: RCWA
version: 4.6.1
date: 2017-12-18
description: |
    Residue-Class-Wise Affine Groups

authors:
    - name: Stefan Kohl
      url: https://stefan-kohl.github.io/

maintainers:
    - name: Stefan Kohl
      url: https://stefan-kohl.github.io/

GAP: ">=4.8.7"

needed-pkgs:
    - name: "ResClasses"
      version: ">=4.7.0"
      url: "https://stefan-kohl.github.io/resclasses.html"
    - name: "GRAPE"
      version: ">=4.7"
      url: "http://www.maths.qmul.ac.uk/~leonard/grape/"
    - name: "Polycyclic"
      version: ">=2.11"
      url: "https://gap-packages.github.io/polycyclic/"
    - name: "FR"
      version: ">=2.2.1"
      url: "https://gap-packages.github.io/fr"
    - name: "GAPDoc"
      version: ">=1.5.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "Utils"
      version: ">=0.40"
      url: "https://gap-packages.github.io/utils"

www: https://stefan-kohl.github.io/rcwa.html
readme: README.rcwa
packageinfo: https://stefan-kohl.github.io/rcwa/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://stefan-kohl.github.io/rcwa/rcwa-4.6.1.tar.gz

abstract: |
    This package provides implementations of algorithms and methods for computation in certain infinite permutation groups. For an abstract, see <a href = "https://stefan-kohl.github.io/rcwa.html">here</a>.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
